name: Docker Gutzkow Deployment

on:
  push:
    tags:
      - 'gutzkow*'

jobs:
  build-base-image:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/gutzkow}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: scmmmh
        password: ${{ secrets.DOCKERACCESSTOKEN }}

    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: docker/gutzkow
        push: true
        tags: scmmmh/digitaleditioneditor:${{ steps.branch_name.outputs.SOURCE_TAG }}
